# This is a basic workflow to help you get started with Actions

name: PyInstaller

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
#  centos7:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#    - uses: actions/checkout@v1
#    - name: Set up Python 3.8
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.8
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pyinstaller
#    - name: build with pyinstaller
#      run: |
#        pyinstaller csv2json_mskinventory.py
#    - name: Upload centos 7
#      uses: actions/upload-artifact@v1
#      with:
#        name: csv2json_mskinventory
#        path: dist/csv2json_mskinventory

  # This workflow contains a single job called "build"
  windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        echo "python -m pip install --upgrade pip"
        pip install pyinstaller
    - name: build with pyinstaller
      run: |
        pyinstaller csv2json_mskinventory.py
    - name: Dir
      run: |
        pwd
        dir
    - name: Upload centos 7
      uses: actions/upload-artifact@v1
      with:
        name: csv2json_mskinventory
        path: dist\csv2json_mskinventory.exe